export enum CategorieFrais {
    TAXE_FONCIERE = "TAXE_FONCIERE",
    IMPOTS_SUR_LE_REVENU = "IMPOTS_SUR_LE_REVENU",
    CHARGES_COPROPRIETE = "CHARGES_COPROPRIETE",
    ASSURANCE_PROPRIETAIRE = "ASSURANCE_PROPRIETAIRE",
    FRAIS_GESTION_LOCATIVE = "FRAIS_GESTION_LOCATIVE",
    ENTRETIEN = "ENTRETIEN",
    TRAVAUX = "TRAVAUX",
    REMBOURSEMENT_PRET = "REMBOURSEMENT_PRET",
    IMPOTS_SUR_LOYER = "IMPOTS_SUR_LOYER",
    FRAIS_NOTARIAUX = "FRAIS_NOTARIAUX",
    FRAIS_AGENT_IMMO = "FRAIS_AGENT_IMMO",
    DEPENSES_OCCASIONNELLES = "DEPENSES_OCCASIONNELLES",
    FRAIS_DIVERS = "FRAIS_DIVERS"
}
